# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criaçao', models.CharField(max_length=200)),
                ('tipo_despesa', models.CharField(choices=[('Roupas', 'Roupas'), ('Remedio', 'Remédio'), ('Alimentaçao', 'Alimentaçao'), ('Educaçao', 'Eduçação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=1000)),
                ('descriçao', models.CharField(max_length=200)),
                ('forma_pagamento', models.CharField(choices=[('Dinherio', 'Dinheiro'), ('Cartao de Credito', 'Cartao de Credito'), ('Cartao Debito', 'Cartao Debito'), ('Cartao Crediario', 'Cartao Crediario'), ('Cheque', 'Cheque')], max_length=1000)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
